In [9]:
#1.Python Programming Basics
#Task-1
#1.Write a Python function that takes a list of numbers and returns a new list with each number squared.

def square_list(numbers):
    squared = [num ** 2 for num in numbers]
    return squared

#2. Create a list of 10 integers, use your function to square these numbers, and print the original and squared lists.

original_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
squared_list = square_list(original_list)
print("Original List:", original_list)
print("Squared List: ", squared_list)

Original List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Squared List:  [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [8]:
#Task-2
#1.Create a dictionary where the keys are names of students and the values are their scores in an exam.

student_scores = {'Nikhil': 85,'Saloni': 97,'Niki': 52,'Lalu': 39,'Akku': 75,'Fatima': 91}

#2.Write a function that takes this dictionary and returns a new dictionary with only those students who scored above 50.

def scores_above_50(scores_dict):
    now = {name: score for name, score in scores_dict.items() if score > 50}
    return now
    
#3.Use adictionary comprehension to create a dictionary where the keys are student names and the values are 
    #their scores multiplied by 1.1 (e.g., adding 10% to the score).

bonus_scores = {name: round(score * 1.1, 1) for name, score in student_scores.items()}

print("Original Scores:")
print(student_scores)

print("\nStudents with Scores Above 50:")
print(scores_above_50(student_scores))

print("\nScores After 10% Bonus:")
print(bonus_scores)

Original Scores:
{'Nikhil': 85, 'Saloni': 97, 'Niki': 52, 'Lalu': 39, 'Akku': 75, 'Fatima': 91}

Students with Scores Above 50:
{'Nikhil': 85, 'Saloni': 97, 'Niki': 52, 'Akku': 75, 'Fatima': 91}

Scores After 10% Bonus:
{'Nikhil': 93.5, 'Saloni': 106.7, 'Niki': 57.2, 'Lalu': 42.9, 'Akku': 82.5, 'Fatima': 100.1}


In [14]:
#2.Data Manipulation with Pandas
#Task-1
#Use the following dictionary to create a Pandas DataFrame:
#data = {
#'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
#'Age': [25, 30, 35, 40, 45],
#'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
#}

import pandas as pd
data = {
    'Name': ['Nikhil', 'Saloni', 'Charlie', 'King', 'Ronaldo'],
    'Age': [22, 21, 35, 40, 45],
    'City': ['Hongkong', 'USA', 'Thailand', 'India', 'Russia']
}

#1.Create a DataFrame from this dictionary.

df = pd.DataFrame(data)

#2.Display the first few rows of the DataFrame.

print("DataFrame:")
print(df.head())

#3. Calculate and print the average age from the DataFrame.

average_age = df['Age'].mean()
print("\nAverage Age:", average_age)

DataFrame:
      Name  Age      City
0   Nikhil   22  Hongkong
1   Saloni   21       USA
2  Charlie   35  Thailand
3     King   40     India
4  Ronaldo   45    Russia

Average Age: 32.6


In [18]:
#Task-2
#1.Filter the DataFrame to include only rows where the age is greater than 30.

import pandas as pd
data = {
    'Name': ['Nikhil', 'Saloni', 'Charlie', 'King', 'Ronaldo'],
    'Age': [22, 21, 35, 40, 45],
    'City': ['Hongkong', 'USA', 'Thailand', 'India', 'Russia']
}

df = pd.DataFrame(data)
filtered_df = df[df['Age'] > 30]
print("Filtered DataFrame (Age > 30):")
print(filtered_df)

#2.Add anewcolumn to the DataFrame called AgeGroup, where the value is 'Senior' if age is greater than or equal to 40, otherwise 'Adult'.

df['AgeGroup'] = df['Age'].apply(lambda age: 'Senior' if age >= 40 else 'Adult')
print("\nDataFrame with AgeGroup column:")
print(df)

#3.Group the data by AgeGroup and calculate the average age for each group

avg_age = df.groupby('AgeGroup')['Age'].mean()
print("\nAverage Age by AgeGroup:")
print(avg_age)

Filtered DataFrame (Age > 30):
      Name  Age      City
2  Charlie   35  Thailand
3     King   40     India
4  Ronaldo   45    Russia

DataFrame with AgeGroup column:
      Name  Age      City AgeGroup
0   Nikhil   22  Hongkong    Adult
1   Saloni   21       USA    Adult
2  Charlie   35  Thailand    Adult
3     King   40     India   Senior
4  Ronaldo   45    Russia   Senior

Average Age by AgeGroup:
AgeGroup
Adult     26.0
Senior    42.5
Name: Age, dtype: float64


In [19]:
#3.Data Manipulation with NumPy
#Task-1
#1.Create a NumPy array with 12 random integers between 1 and 50.

import numpy as np
array = np.random.randint(1, 51, size=12)
print("Original Array:")
print(array)

#2.Reshape the array into a 3x4 matrix.

matrix = array.reshape(3, 4)
print("\nReshaped 3x4 Matrix:")
print(matrix)

#3.Find and print the maximum, minimum, and mean values of the array.

max_val = np.max(array)
min_val = np.min(array)
mean_val = np.mean(array)

print("\nMaximum Value:", max_val)
print("Minimum Value:", min_val)
print("Mean Value:   ", round(mean_val, 2))

Original Array:
[36 22 31 15 48 15 46 24 45  6 46 27]

Reshaped 3x4 Matrix:
[[36 22 31 15]
 [48 15 46 24]
 [45  6 46 27]]

Maximum Value: 48
Minimum Value: 6
Mean Value:    30.08


In [20]:
#Task-2
#1.Create a NumPy array of shape (4, 3) with values from 1 to 12.

import numpy as np
array = np.arange(1, 13).reshape(4, 3)
print("Original Array (4x3):")
print(array)

#2.Extract and print the second row of the array.

second_row = array[1]
print("\nSecond Row:")
print(second_row)

#3.Extract and print a 2x2 submatrix from the top-left corner of the array.

submatrix = array[0:2, 0:2]
print("\n2x2 Submatrix (Top-Left Corner):")
print(submatrix)

Original Array (4x3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Second Row:
[4 5 6]

2x2 Submatrix (Top-Left Corner):
[[1 2]
 [4 5]]
