In [5]:
import numpy as np

array_1d=np.array([1,2,3,4,5])
print("1D Array:",array_1d)

array_2d=np.array([[1,2,3],[4,5,6]])
print("2D Array:\n",array_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [6]:
zeros_array=np.zeros((3,4))
print("Array of zeros:\n",zeros_array)

Array of zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
ones_array=np.ones(5)
print("Array of ones:",ones_array)

Array of ones: [1. 1. 1. 1. 1.]


In [9]:
range_array=np.arange(10)
print("Range Array:",range_array)

Range Array: [0 1 2 3 4 5 6 7 8 9]


In [12]:
linspace_array=np.linspace(0,1,5)
print("Linspace array:",linspace_array)

Linspace array: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
print("Shape of array_2d:"
print("Size of array_2d:"