In [4]:
import numpy as np

array_1d=np.array([10,20,30,40,50])
print("Element at index 2:",array_1d[2])

Element at index 2: 30


In [5]:
print("Last element:",array_1d[-1])
print("Second-to-last-element:",array_1d[-2])

Last element: 50
Second-to-last-element: 40


In [4]:
import numpy as np
array_2d=np.array([[10,20,30],[40,50,60]])
print("Element at (1,2):",array_2d[1,2])

Element at (1,2): 60


In [7]:
print("Second row:",array_2d[1])
print("First column:",array_2d[:,0])

Second row: [40 50 60]
First column: [10 40]


In [8]:
boolean_index=array_2d[array_2d>30]
print("Elements greater than 30:",boolean_index)

Elements greater than 30: [40 50 60]


In [9]:
print("Elements at indices 0 and 2 of the first row:",array_2d[0,[0,2]])

Elements at indices 0 and 2 of the first row: [10 30]


In [10]:
array_1d=np.array([10,20,30,40,50])
slice_id=array_1d[1:4]
print("Slice id:",slice_id)

Slice id: [20 30 40]


In [12]:
slice_step_1d=array_1d[0:5:2]
print("Sliced 1d array:",slice_step_1d)

Sliced 1d array: [10 30 50]


In [18]:
array_2d=np.array([[10,20,30],[40,50,60],[70,80,90]])
slice_2d=array_2d[:2,:2]
print("Slced 2d array:\n",slice_2d)

Slced 2d array:
 [[10 20]
 [40 50]]


rows_2d=array_2d[:2]
print("First two rows:\n:",rows_2d)


In [20]:
rows_2d=array_2d[:2]
print("First two rows:\n",rows_2d)

last_column_2d=array_2d[:,-1]
print("Last column:\n",last_column_2d)

First two rows:
 [[10 20 30]
 [40 50 60]]
Last column:
 [30 60 90]


In [22]:
step_rows_2d=array_2d[::2]
print("Every other row:\n",step_rows_2d)

step_columns_2d=array_2d[:,::2]
print("Every other column:\n",step_columns_2d)

Every other row:
 [[10 20 30]
 [70 80 90]]
Every other column:
 [[10 30]
 [40 60]
 [70 90]]
